#Testing
name: Testing Project

on:
  pull_resquest:
    branches:
      ["master"]

jobs:
  test:
    runs_on: ubuntu-latest
    container:
      images: node:20
    steps:
      - uses: actions/checkout@v3
        with: node-version: 20
      - run: npm ci
      - run: npm test 
      - run: npm run build 
