#Testing
name: Testing Project

on:
  pull_resquest:
    branches:
      ["master"]

jobs:
  test:
    run_on: ubuntu-latest
    container:
      images: node:20
    steps:
      - uses: action/checkout@v4
        with: node-version: 20
      - run: npm ci
      - run: npm test 
      - run: npm run build 
